# Install perfsonar roles
- src: https://github.com/UMNET-perfSONAR/ansible-role-bootstrap-dell.git
#- src: https://github.com/UMNET-perfSONAR/ansible-role-ansible.git
#- src: https://github.com/UMNET-perfSONAR/ansible-role-vagrant.git
#- src: https://github.com/UMNET-perfSONAR/ansible-role-virtualbox.git
#- src: https://github.com/UMNET-perfSONAR/ansible-role-pscheduler.git
