# Install perfsonar roles
- src: https://github.com/UMNET-perfSONAR/ansible-role-bootstrap-dell.git
- src: https://github.com/UMNET-perfSONAR/ansible-role-ansible-dell.git
- src: https://github.com/UMNET-perfSONAR/ansible-role-vagrant-dell.git
- src: https://github.com/UMNET-perfSONAR/ansible-role-virtualbox-dell.git


